"""empty message

Revision ID: 2d68f814f835
Revises: 
Create Date: 2022-03-20 03:59:27.755904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d68f814f835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_title', sa.String(length=100), nullable=False),
    sa.Column('prop_desc', sa.String(length=300), nullable=False),
    sa.Column('prop_room_count', sa.Integer(), nullable=False),
    sa.Column('prop_bathroom_count', sa.Float(), nullable=False),
    sa.Column('prop_price', sa.Float(), nullable=False),
    sa.Column('prop_type', sa.String(length=10), nullable=False),
    sa.Column('prop_location', sa.String(length=100), nullable=False),
    sa.Column('prop_photo', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
